const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'lineageData.ts');

const SHOPIFY_DATA_NODES = [
  {
    id: 'shopify',
    name: 'Shopify',
    type: 'company',
    year: 2006,
    description: 'The modern commerce engine — Canada\'s most successful contemporary tech giant.',
    relationship: 'Root Entity',
    isUnicorn: true,
    unicornRegion: 'Canadian',
    category: 'strategic_partner',
    shopifyConnection: 'Root Founder Hub',
    industryFocus: 'E-commerce Platform'
  },
  // 2013
  {
    id: 'stripe',
    name: 'Stripe',
    type: 'company',
    parent: 'shopify',
    year: 2013,
    description: 'Powers Shopify Payments and core financial infrastructure.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: '>$350M invested since 2013',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Global Payment Infrastructure'
  },

  // 2016
  {
    id: 'rhenti',
    name: 'Rhenti',
    type: 'company',
    parent: 'shopify',
    year: 2016,
    description: 'Rental and leasing automation platform for real estate.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'C$4.1M',
    shopifyConnection: 'Erin Chan (Senior Product Manager)',
    industryFocus: 'Real Estate & Leasing Automation'
  },

  // 2017
  {
    id: 'clever-few',
    name: 'Clever Few (Parcelify)',
    type: 'company',
    parent: 'shopify',
    year: 2017,
    description: 'Custom-shipping rates app for Shopify stores.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Richard Blair (Software Developer)',
    industryFocus: 'E-commerce Logistics & Shipping'
  },
  {
    id: 'the-good-internet',
    name: 'The Good Internet',
    type: 'company',
    parent: 'shopify',
    year: 2017,
    description: 'Network of companies helping creators build businesses.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Zack Honarvar (Enterprise Sales)',
    industryFocus: 'Creator Economy Infrastructure'
  },
  {
    id: 'nine-and-two',
    name: 'Nine And Two Consulting',
    type: 'company',
    parent: 'shopify',
    year: 2017,
    description: 'Consultancy helping companies build partnership programs.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Dan Eveleigh (Head of Partnerships)',
    industryFocus: 'Partnership Program Strategy'
  },
  {
    id: 'win-brands',
    name: 'WIN Brands',
    type: 'company',
    parent: 'shopify',
    year: 2017,
    description: 'E-commerce brand aggregator platform.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: '$201M to date',
    shopifyConnection: 'Taylor Sicard (Partner Manager)',
    industryFocus: 'E-commerce Brand Aggregation'
  },
  {
    id: 'archetype-themes',
    name: 'Archetype Themes',
    type: 'company',
    parent: 'shopify',
    year: 2017,
    description: 'Tools to design top-selling Shopify themes (acquired 2022).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Self funded',
    shopifyConnection: 'P. Pritchard (Designer) & C. Shold (Developer)',
    industryFocus: 'Shopify Theme Architecture',
    status: 'acquired'
  },

  // 2019
  {
    id: 'bobby',
    name: 'Bobby',
    type: 'company',
    parent: 'shopify',
    year: 2019,
    description: 'Independent game development studio.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Gabriel O\'Flaherty-Chan (Developer)',
    industryFocus: 'Game Development Studio'
  },
  {
    id: 'trexity',
    name: 'Trexity',
    type: 'company',
    parent: 'shopify',
    year: 2019,
    description: 'Last-mile delivery and local logistics network.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Over $6.5M raised',
    shopifyConnection: 'Alok Ahuja (Ops Director, Marketplace)',
    industryFocus: 'Last-Mile Logistics'
  },
  {
    id: 'domaine',
    name: 'Domaine',
    type: 'company',
    parent: 'shopify',
    year: 2019,
    description: 'Enterprise Shopify design & development practice.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Backed by BV Investment Partners',
    shopifyConnection: 'Mac King (Partner Manager)',
    industryFocus: 'E-commerce Engineering Practice'
  },

  // 2020
  {
    id: 'affirm',
    name: 'Affirm Holdings',
    type: 'company',
    parent: 'shopify',
    year: 2020,
    description: 'Buy-now-pay-later checkout financing (IPOed at $2B).',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Warrants worth $2B at 2021 IPO',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Fintech / BNPL Financing'
  },
  {
    id: 'maple-app',
    name: 'Maple',
    type: 'company',
    parent: 'shopify',
    year: 2020,
    description: 'Household task and family management technology.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 5,
    capitalRaised: '$3.5M (2021)',
    shopifyConnection: 'Mike Taylor (Eng) & Michael Perry (Product)',
    industryFocus: 'Consumer Household Tech'
  },
  {
    id: 'afterword',
    name: 'Afterword',
    type: 'company',
    parent: 'shopify',
    year: 2020,
    description: 'Tech platform and AI tool for funeral parlours.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Effie Anolik (Internal/Customer Ops)',
    industryFocus: 'End-of-Life & Legacy Services'
  },
  {
    id: 'alumworks',
    name: 'Alumworks',
    type: 'company',
    parent: 'shopify',
    year: 2020,
    description: 'Built suite of Shopify merchant apps (Alpaca, Thresher, Parrot).',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'J. Gosse (Dev), J. Normore (Eng), R. Langlois (Design)',
    industryFocus: 'Shopify Merchant App Suite'
  },

  // 2021
  {
    id: 'gadget',
    name: 'Gadget',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Full-stack serverless developer platform for Shopify apps.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 8,
    capitalRaised: '$8.5M',
    shopifyConnection: 'Harry Brundage (Director, Product)',
    industryFocus: 'Developer Infrastructure'
  },
  {
    id: 'alacart-apps',
    name: 'Alacart Apps',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Specialists in preparing online items as custom gifts.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 5,
    capitalRaised: 'Largely self funded',
    shopifyConnection: 'Adam Doeler (Senior Staff Engineer)',
    industryFocus: 'E-commerce Gifting Tools'
  },
  {
    id: 'returnbear',
    name: 'ReturnBear',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'End-to-end product returns platform (acquired 2026).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'VC & partner backed',
    shopifyConnection: 'Sylvia Ng (GM, Start Product Line)',
    industryFocus: 'Reverse Logistics & Returns',
    status: 'acquired'
  },
  {
    id: 'supergreat',
    name: 'Supergreat',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Live-streaming social commerce app (acquired 2023).',
    relationship: 'Strategic Partner (Acquired)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $20M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Social Commerce & Streaming',
    status: 'acquired'
  },
  {
    id: 'pluto',
    name: 'Pluto',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Corporate cards and spend management platform.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: '>$10.1M (up to 2025)',
    shopifyConnection: 'Mohammed Ridwan & Nayeem Zen (Product)',
    industryFocus: 'Corporate Spend Management'
  },
  {
    id: 'disco',
    name: 'Disco (Co-op Commerce)',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Post-purchase merchant network for cross-brand upsells.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $26M raised',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Post-Purchase Merchandising'
  },
  {
    id: 'creative-layer',
    name: 'Creative Layer',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Print-on-demand personalization software for products.',
    relationship: 'Alumni/Exec Lead Investor',
    category: 'lead_investment',
    capitalRaised: 'C$3M Seed funding',
    shopifyConnection: 'Tobi Lütke (CEO), Cody Fauser (ex-CTO), A. McNamara (ex-VP)',
    industryFocus: 'Print-on-Demand Tech'
  },
  {
    id: 'yotpo',
    name: 'Yotpo',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Trustworthy product reviews and loyalty engine for merchants.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Contributed $30M corporate round',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Customer Reviews & Loyalty'
  },
  {
    id: 'tapcart',
    name: 'Tapcart',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Mobile app builder enabling merchants to create native apps.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $50M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Mobile App Builder'
  },
  {
    id: 'global-e',
    name: 'Global-E Online',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Cross-border sales platform (6% equity stake worth $490M at IPO).',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: '6% equity stake ($490M at IPO)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Cross-Border E-commerce'
  },
  {
    id: 'codat',
    name: 'Codat',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'API engine to access small business financial data.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $100M round (2022)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'SMB Data API Infrastructure'
  },
  {
    id: 'loop-returns',
    name: 'Loop Returns',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Software for Shopify product returns and exchanges.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $65M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Returns Management'
  },
  {
    id: 'pipe',
    name: 'Pipe Technologies',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Financing platform lending against recurring revenues of stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $50M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Recurring Revenue Financing'
  },
  {
    id: 'swyft',
    name: 'Swyft',
    type: 'company',
    parent: 'shopify',
    year: 2021,
    description: 'Connects Shopify stores to local couriers for same-day delivery.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in C$22M Seed',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Same-Day Courier Delivery'
  },

  // 2022
  {
    id: 'downpay',
    name: 'Downpay',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Layaways app for made-to-order, high-value products without credit checks.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Diana Birsan (Product Lead) & Denis Zgonjanin (Developer)',
    industryFocus: 'Layaways & Deposits'
  },
  {
    id: 'storehero',
    name: 'StoreHero',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Profit analytics tool for e-commerce businesses.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: '€600K Pre-Seed raised',
    shopifyConnection: 'Tom Gleeson (Merchant Success Manager)',
    industryFocus: 'E-commerce Profit Analytics'
  },
  {
    id: 'wati',
    name: 'WATI',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Personalized customer notifications via WhatsApp.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $23M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'WhatsApp Messaging Automation'
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Leading email & SMS marketing platform ($100M investment in 2022).',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Shopify invested $100M (2022)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Email & SMS Marketing'
  },
  {
    id: 'clean-canvas',
    name: 'Clean Canvas',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Develops premium store themes (acquired 2025).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Marcus Seoighe (Manager of Partner Themes)',
    industryFocus: 'Store Theme Engineering',
    status: 'acquired'
  },
  {
    id: 'single',
    name: 'Single',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Music & digital merchandise commerce app.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Music Commerce Engine'
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'AI-driven support answers & chat platform.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Co-led $30M Series C',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'AI Customer Helpdesk'
  },
  {
    id: 'thirdweb',
    name: 'Thirdweb',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Web3 developer SDKs to simplify building blockchain features.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $24M Series A',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Web3 Developer Infrastructure'
  },
  {
    id: 'saltz-app',
    name: 'Saltz.app',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'B2B food distribution digital marketplace.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: '$3.2M Seed (2024); €20M Series A (2026)',
    shopifyConnection: 'Andrius Slimas (Director of Product)',
    industryFocus: 'B2B Food Supply Marketplace'
  },
  {
    id: 'crossing-minds',
    name: 'Crossing Minds',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'AI-powered recommendation engine (acquired 2025). Led by Shopify.',
    relationship: 'Alumni/Exec Lead Investor (Acquired)',
    category: 'lead_investment',
    capitalRaised: 'Led investment of US$14.8M',
    shopifyConnection: 'Shopify Ventures & Execs (Lead Investor)',
    industryFocus: 'AI Product Recommendation Engine',
    status: 'acquired'
  },
  {
    id: 'select',
    name: 'SELECT',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Optimization and cost control platform for data (acquired 2026).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Ian Whitestone (Lead Data Scientist)',
    industryFocus: 'Snowflake/Data Cost Optimization',
    status: 'acquired'
  },
  {
    id: 'centro-commerce',
    name: 'Centro Commerce',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'AI procurement for inventory & supply chains (acquired 2025).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Raised $2M pre-seed',
    shopifyConnection: 'Jamyang Tenzin (Marketing Manager)',
    industryFocus: 'AI Supply Chain Procurement',
    status: 'acquired'
  },
  {
    id: 'growth-crew',
    name: 'Growth Crew',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Helps e-commerce businesses scale growth & revenue.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Brent Stirling (Performance Marketing Manager)',
    industryFocus: 'Growth Marketing Advisory'
  },
  {
    id: 'abra-promotions',
    name: 'Abra Promotions',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'App applying dynamic discounts at checkout.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Total over $104M raised',
    shopifyConnection: 'Dan Patricio (Product Dev) & R. Macdonald (Developer)',
    industryFocus: 'Checkout Dynamic Discounting'
  },
  {
    id: 'shippo',
    name: 'Shippo',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Global multi-carrier shipping API platform.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed (Unicorn Valuation)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Global Shipping Infrastructure'
  },
  {
    id: 'citylitics',
    name: 'Citylitics',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'AI tool for finding procurement opportunities in documents. Led by John Phillips.',
    relationship: 'Alumni/Exec Lead Investor',
    category: 'lead_investment',
    capitalRaised: 'Led C$6.2M Series A',
    shopifyConnection: 'John Phillips (ex-Board Director - Lead Investor)',
    industryFocus: 'AI Infrastructure Procurement'
  },
  {
    id: 'uptime',
    name: 'Uptime',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Proactive alerts and incident response for Shopify store issues.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Taylor Sicard (Partner Manager)',
    industryFocus: 'Store Operations Uptime Monitoring'
  },
  {
    id: 'creator-now',
    name: 'Creator Now',
    type: 'company',
    parent: 'shopify',
    year: 2022,
    description: 'Creator education and community platform (acquired 2024).',
    relationship: 'Alumni Startup (Acquired)',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: '$3M',
    shopifyConnection: 'Zack Honarvar (Sales Rep)',
    industryFocus: 'Creator Education Platform',
    status: 'acquired'
  },

  // 2023
  {
    id: 'data-gardeners',
    name: 'Data Gardeners',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Mining databases for business insights and monetization.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Ben Doyle (Data Lead) & Dana Klassen (Data Lead)',
    industryFocus: 'Database Intelligence & Analytics'
  },
  {
    id: 'triple-whale',
    name: 'Triple Whale',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Consolidates e-commerce analytics into one AI-driven dashboard.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $25M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'E-commerce AI Analytics'
  },
  {
    id: 'boom-vision',
    name: 'Boom Vision',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'App for studio quality videos over Zoom and conferencing.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 5,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Robleh Jama (Product Director)',
    industryFocus: 'Video Enhancement Software'
  },
  {
    id: 'faire',
    name: 'Faire',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Wholesale B2B marketplace recommended for Shopify stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Equity stake (Undisclosed)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Wholesale Marketplace'
  },
  {
    id: 'storelocators',
    name: 'StoreLocators',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Locates offline stores holding inventory items from online stores.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Ivan Sanchez (Lead, Data Scientist)',
    industryFocus: 'Omnichannel Inventory Location'
  },
  {
    id: 'trig-ai',
    name: 'Trig.ai',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'AI-driven account management and automated customer success.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: '$10M Seed rounds',
    shopifyConnection: 'Mark Ryan (Product Manager)',
    industryFocus: 'AI Account Management'
  },
  {
    id: 'turbopuffer',
    name: 'Turbopuffer',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Fast AI vector search engine that cuts costs and scales.',
    relationship: 'Alumni Startup',
    isUnicorn: true,
    unicornRegion: 'Canadian',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: '<C$1M pre-Seed (2023)',
    shopifyConnection: 'Justine Li & Simon Hørup Eskildsen (Engineers)',
    industryFocus: 'AI Vector Search Engine'
  },
  {
    id: 'storycraft',
    name: 'Storycraft',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'AI-powered game building tool.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Total of $5M raised to date',
    shopifyConnection: 'Adam Waseluk (UX/Product Design)',
    industryFocus: 'AI Game Creation'
  },
  {
    id: 'nomba',
    name: 'Nomba',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Financial services and payment solutions for African merchants.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $30M pre-Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'African Financial Services'
  },
  {
    id: 'hubtree',
    name: 'HubTree Talent',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Talent recruitment and executive search firm.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Lindsay Godson',
    industryFocus: 'Tech Recruitment'
  },
  {
    id: 'ask-kenna',
    name: 'Ask Kenna',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Specialized consulting service for Shopify Plus merchants.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Kenna Brown (Launch Engineer - Shopify Plus)',
    industryFocus: 'Shopify Plus Advisory'
  },
  {
    id: 'flexport',
    name: 'Flexport',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Global freight & logistics for merchant orders (20% equity stake).',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: '20% Equity Stake',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Global Freight & Freight Forwarding'
  },
  {
    id: 'soarce',
    name: 'Soarce Consulting',
    type: 'company',
    parent: 'shopify',
    year: 2023,
    description: 'Staffing & recruiting for tech and e-commerce scaling firms.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Hilary Smith (Account Executive)',
    industryFocus: 'E-commerce Talent Staffing'
  },

  // 2024
  {
    id: 'liquid-ai',
    name: 'Liquid AI',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'AI recommendation and search foundation models for stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $250M Series A',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'AI Search & Recommendation Models'
  },
  {
    id: 'melio',
    name: 'Melio',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'B2B payments platform for Shopify merchants (exited 2025).',
    relationship: 'Strategic Partner (Exited 2025)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $150M Series E',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'B2B Payment Processing',
    status: 'exited'
  },
  {
    id: 'reactiv',
    name: 'Reactiv',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'Native iOS and Android mobile app builder for merchants.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: 'Over $5M in seed funding',
    shopifyConnection: 'Ross Correia (Sales) & Zack Elias (Partnerships)',
    industryFocus: 'Native Mobile Apps'
  },
  {
    id: 'lightdash',
    name: 'Lightdash',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'AI business intelligence tool for Shopify stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $11M raise',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'AI Business Intelligence'
  },
  {
    id: 'symmetry-commerce',
    name: 'Symmetry Commerce',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'E-commerce platform migrations and custom integrations.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Michael Kiss (Enterprise Lead) & Io Hanson (Lead Engineer)',
    industryFocus: 'E-commerce Migration Engineering'
  },
  {
    id: 'physical-intelligence',
    name: 'Physical Intelligence',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'AI foundation models for training physical warehouse robots.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    isUnicorn: true,
    unicornRegion: 'US / Global',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed (Unicorn Valuation)',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Robotics & Physical AI'
  },
  {
    id: 'lantern',
    name: 'Lantern',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'Customer engagement and retention software on Shopify.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 5,
    capitalRaised: '$6.8M seed round',
    shopifyConnection: 'Kyle Peatt (Co-founder, Design Lead)',
    industryFocus: 'Customer Retention Tech'
  },
  {
    id: 'page',
    name: 'Page',
    type: 'company',
    parent: 'shopify',
    year: 2024,
    description: 'Advanced tech & AI for insight into government activities.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 6,
    capitalRaised: 'Raised $4.1M in seed funding',
    shopifyConnection: 'Ben Cox (Director, Product Engineering)',
    industryFocus: 'Government Tech & Intelligence'
  },

  // 2025
  {
    id: 'sparrow-bioacoustics',
    name: 'Sparrow BioAcoustics',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'App turns smartphone into stethoscope. Led by John Phillips.',
    relationship: 'Alumni/Exec Lead Investor',
    category: 'lead_investment',
    capitalRaised: 'Led C$10M (2025) & C$13M seed (2024)',
    shopifyConnection: 'John Phillips (ex-Board Director - Lead Investor)',
    industryFocus: 'Medical Health Diagnostics'
  },
  {
    id: 'tempo',
    name: 'Tempo',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Layer-1 blockchain built for high-scale commerce on Shopify.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Layer-1 Blockchain'
  },
  {
    id: 'fal-ai',
    name: 'Fal.ai',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Multimodal AI models for Shopify developers.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $125M Series C',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Multimodal AI Media'
  },
  {
    id: 'sanity',
    name: 'Sanity',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Headless Content Management infrastructure on Shopify.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $85M Series C',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Headless CMS Architecture'
  },
  {
    id: 'graphite',
    name: 'Graphite',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'AI coding tool for Shopify developers (exited).',
    relationship: 'Strategic Partner (Exited)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $52M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'AI Code Generation',
    status: 'exited'
  },
  {
    id: 'medda-tech',
    name: 'Medda Technologies',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Digital platform for medical staff to access patient health histories.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 2,
    capitalRaised: 'Self funded',
    shopifyConnection: 'Gareth du Plooy (Engineer)',
    industryFocus: 'Digital Health Records'
  },
  {
    id: 'fundthrough',
    name: 'FundThrough',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Fintech invoice factoring for SMBs. Led by John Phillips.',
    relationship: 'Alumni/Exec Lead Investor',
    category: 'lead_investment',
    capitalRaised: 'Led $25M Series B',
    shopifyConnection: 'John Phillips (ex-Board Director - Lead Investor)',
    industryFocus: 'Fintech Invoice Factoring'
  },
  {
    id: 'whalar',
    name: 'Whalar Group',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Infrastructure for creator businesses on Shopify.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Creator Business Infrastructure'
  },
  {
    id: 'settle',
    name: 'Settle',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'B2B e-commerce finance tool for Shopify stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Undisclosed',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'B2B Commerce Financing'
  },
  {
    id: 'crstl',
    name: 'Crstl',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Agentic B2B commerce network on Shopify.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $10M Series A',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Agentic B2B Network'
  },
  {
    id: 'reown',
    name: 'Reown',
    type: 'company',
    parent: 'shopify',
    year: 2025,
    description: 'Crypto user interface protocol for Web3 on Shopify.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $13M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'Crypto & Web3 Interfaces'
  },

  // 2026
  {
    id: 'gumloop',
    name: 'Gumloop',
    type: 'company',
    parent: 'shopify',
    year: 2026,
    description: 'AI automation workflows for e-commerce stores.',
    relationship: 'Strategic Partner (Shopify Ventures)',
    category: 'strategic_partner',
    capitalRaised: 'Participated in $50M Series B',
    shopifyConnection: 'Shopify Ventures',
    industryFocus: 'AI Automation Workflows'
  },
  {
    id: 'stilla',
    name: 'Stilla',
    type: 'company',
    parent: 'shopify',
    year: 2026,
    description: 'AI agent keeps track of conversations, tasks, and motion.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 3,
    capitalRaised: '$5M Seed round',
    shopifyConnection: 'S. Ghorbani (VP Eng) & K. Drobin (Product Lead)',
    industryFocus: 'AI Productivity Agents'
  },
  {
    id: 'sapiom',
    name: 'Sapiom',
    type: 'company',
    parent: 'shopify',
    year: 2026,
    description: 'Give AI agents API access so they can buy, sell & negotiate.',
    relationship: 'Alumni Startup',
    category: 'alumni',
    alumniTenureYears: 4,
    capitalRaised: '$15.8M Seed round',
    shopifyConnection: 'Ilan Zerbib (Director of Engineering)',
    industryFocus: 'Autonomous Agent Payments API'
  }
];

let content = fs.readFileSync(filePath, 'utf-8');

const shopifyDataRegex = /export const SHOPIFY_DATA: LineageNode\[\] = \[\s*[\s\S]*?\n\];/;
const newCode = `export const SHOPIFY_DATA: LineageNode[] = ${JSON.stringify(SHOPIFY_DATA_NODES, null, 2)};`;

if (!shopifyDataRegex.test(content)) {
  console.error("Could not find SHOPIFY_DATA regex match in lineageData.ts!");
  process.exit(1);
}

content = content.replace(shopifyDataRegex, newCode);
fs.writeFileSync(filePath, content, 'utf-8');
console.log(`Successfully updated SHOPIFY_DATA with ${SHOPIFY_DATA_NODES.length} nodes (Canadian & US/Global Unicorn regions attached).`);
